### ISSUE TITLE
Image URL doesn’t resolve

### ISSUE THREAD

**Issue by brandondurham** [webpack-contrib/url-loader#19]
This may very well be an issue with my setup outside of the url-loader… not sure.

Here is my url-loader config:

``` javascript
loaders: [
    {
        test: /\.(png|jpg|svg)$/,
        loader: 'url?limit=25000'
    }
]
```

In my component’s CSS file I have the following declaration:

``` css
.Base {
    background-color: rgb(83, 96, 108);
    background-image: url('./images/fonts-wallpaper_2x.png');
    background-size: 1760px 248px;
}
```

The url-loader does the proper thing and moves that image to my `publicPath` and updates the url for the image in the resulting CSS:

``` css
.CTA-001__Base-39mzM {
    background-color: rgb(83, 96, 108);
    background-image: url(/include/images/1eb425455da53643003af01f01e8231f.png);
    background-size: 1760px 248px;
}
```

Problem is the image never actually appears in the browser. When I right-click the image URL in the inspector and choose “Open link in new tab” it sends me to this URL:

> chrome-devtools://devtools/include/images/1eb425455da53643003af01f01e8231f.png

If I actually type in the url `http://my.local.site/include/images/1eb425455da53643003af01f01e8231f.png` the image appears.

Any idea what the problem might be?
