### ISSUE TITLE
Multiple references to the same asset in SASS/CSS `url()` breaks replacement process

### ISSUE THREAD

**Issue by HARVS1789UK** [webpack-contrib/url-loader#196]
- Operating System: Windows 10
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.41.2
- url-loader Version: 2.2.0

### Expected Behavior

- Multiple CSS classes reference the same `url-loader` managed asset, for example:
```
.next-button {
    background-image: url('../images/icons/arrow-right.svg');
}
. right-arrow {
    background-image: url('../images/icons/arrow-right.svg');
}
```
- On a build, both of these relative paths are replaced with the data URI representing `arrow-right.svg`

### Actual Behavior

- The first instance is correctly replaced
- The data URI for this asset is discarded (assets are probably held in an array for replacement, array.pop() or similar is called and after the first replacement, discarded)
- The second occurrence is incorrectly replaced with the data URI of whatever my next `url-loader` managed asset for replacement would be (in my case, a Facebook SVG icon)
- This behavior continues for all later replacements, they are all one iteration off
- The second instance is replaced with 

### Code

 webpack.config.js - https://gist.github.com/HARVS1789UK/345ddf7ff48839982a7d3eb744b4510c

```css
.carousel-control-next-icon {
    background-image: url('../images/icons/arrow-right.svg');
}

// Other CSS, then

.icon-arrow {
    background-image: url('../images/icons/arrow-right.svg');
}

.icon-prefix {
    display: inline-block;

    &.facebook {
        background-image: url('../images/icons/facebook-icon.svg');
    }

    &.google-plus {
        background-image: url('../images/icons/google-plus-icon.svg');
    }
}
```

In this scenario, .icon-arrow will have a data URI holding the Facebook icon, .facebook will show a Google Plus icon and .google-plus will be `url(undefined);`

### How Do We Reproduce?

Include references to the same asset in multiple SASS/CSS `url()` definitions, review the output
